"""add translation_segments and glossary_terms tables

Revision ID: 142b2f6f7a0e
Revises: 05927fdf3c4e
Create Date: 2026-09-08 09:49:55.950493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '142b2f6f7a0e'
down_revision = '05927fdf3c4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_user_id'), 'glossary_terms', ['user_id'], unique=False)
    op.create_table('translation_segments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translated_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translated_text_edited', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_segments_segment_id'), 'translation_segments', ['segment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_segments_segment_id'), table_name='translation_segments')
    op.drop_table('translation_segments')
    op.drop_index(op.f('ix_glossary_terms_user_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
