"""add background_volume to projects

Revision ID: 52635470137f
Revises: 66b34c2c5207
Create Date: 2026-09-08 10:38:14.527360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '52635470137f'
down_revision = '66b34c2c5207'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('background_volume', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'background_volume')
    # ### end Alembic commands ###
