"""add voices and dubbed_segments tables

Revision ID: 66b34c2c5207
Revises: 142b2f6f7a0e
Create Date: 2026-09-08 10:08:18.465221

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '66b34c2c5207'
down_revision = '142b2f6f7a0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speaker_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_project_id'), 'voices', ['project_id'], unique=False)
    op.create_table('dubbed_segments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('segment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dubbed_segments_segment_id'), 'dubbed_segments', ['segment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dubbed_segments_segment_id'), table_name='dubbed_segments')
    op.drop_table('dubbed_segments')
    op.drop_index(op.f('ix_voices_project_id'), table_name='voices')
    op.drop_table('voices')
    # ### end Alembic commands ###
